version: '3.4'

services:
  php:
    build:
      context: ./
      dockerfile: ./devops/php/Dockerfile
    restart: always
    volumes:
      - ./devops/php/conf/php-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./web:/var/www/html

  web:
    image: nginx:1
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - php
    restart: always
    volumes:
      - ./devops/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/html
      - ./logs:/var/log/nginx
